### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by CreaturesInUnitards**
had to be done :P

### CODE REVIEW

**Comment by Godje** [comment]
@CreaturesInUnitards I knew that. I was debating should I do that in web-interface on github, or at home, so I don't have to pull. But it seems to be very critical now.

**Comment by CreaturesInUnitards** [comment]
:) I was gunning for "most idiotic PR ever". I think I have a chance!

**Comment by Godje** [comment]
@CreaturesInUnitards that space can actually piss off really hard, so it is not that idiotic. Itiotic would be to remove the space before `oninit` :)
Well, you contributed to `master` branch so this will show up as a contribution on your graph :)

**Comment by CreaturesInUnitards** [comment]
Yay! It’s all about padding the stats 😊

In seriousness though: your code is beautiful. Really nice work.

**Comment by Godje** [comment]
@CreaturesInUnitards thank you :)

**Comment by foucist** [comment]
minor indentation quibble - shouldn't the sourceMatches line up with sourceList?  ( I figure you had it differently at one point and then changed it without re-indenting )

```
const MODEL = {
	search: {
		inputField: m.stream(""),
	},
	sources: {
		sourceList: m.stream([
			
		]),
	sourceMatches: null	}
}
```

vs

```
const MODEL = {
	search: {
		inputField: m.stream(""),
	},
	sources: {
		sourceList: m.stream([ ]),
		sourceMatches: null
	}
}
````

**Comment by Godje** [comment]
I have noticed that too. And didn't fix it for the same reason. I didn't expect so many people reading my code :)
Glad you guys appreciate the greated MVC lib of all time (Mithril)

**Pull request merged**
